// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $Login from "./islands/Login.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
  },
  islands: {
    "./islands/Login.tsx": $Login,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
